SELECT
    NAME,
    CASE
        WHEN BOSS IS NULL THEN "CEO"
        WHEN NAME IN (SELECT DISTINCT BOSS FROM EMPLOYEE_RELATIONSHIPS WHERE BOSS IS NOT NULL) THEN "MANAGER"
        ELSE "WORKER"
    END as BOSS
FROM
    EMPLOYEE_RELATIONSHIPS
ORDER BY
    NAME