SELECT
    u.id AS USER_ID,
    COALESCE(COUNT(p.ITEM), 0) AS PURCHASE_COUNT,
    COALESCE(SUM(c.PRICE), 0) AS TOTAL_PRICE
FROM GAME_USERS u
    LEFT JOIN PURCHASES p ON u.id = p.USER_ID
        LEFT JOIN CHARACTERS c ON p.ITEM = c.NAME
GROUP BY
   u.id;